# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: challenge_action.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import challenge_proto_pb2 as challenge__proto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='challenge_action.proto',
  package='ChallengeAction',
  syntax='proto2',
  serialized_pb=_b('\n\x16\x63hallenge_action.proto\x12\x0f\x43hallengeAction\x1a\x15\x63hallenge_proto.proto\"Z\n\x11\x43hallengeResponse\x12,\n\tchallenge\x18\x01 \x01(\x0b\x32\x19.ChallengeProto.Challenge\x12\x17\n\x0f\x63hallengePassed\x18\x02 \x01(\x08\x42\x33\n com.google.android.finsky.protosB\x0f\x43hallengeAction')
  ,
  dependencies=[challenge__proto__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CHALLENGERESPONSE = _descriptor.Descriptor(
  name='ChallengeResponse',
  full_name='ChallengeAction.ChallengeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='challenge', full_name='ChallengeAction.ChallengeResponse.challenge', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='challengePassed', full_name='ChallengeAction.ChallengeResponse.challengePassed', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=156,
)

_CHALLENGERESPONSE.fields_by_name['challenge'].message_type = challenge__proto__pb2._CHALLENGE
DESCRIPTOR.message_types_by_name['ChallengeResponse'] = _CHALLENGERESPONSE

ChallengeResponse = _reflection.GeneratedProtocolMessageType('ChallengeResponse', (_message.Message,), dict(
  DESCRIPTOR = _CHALLENGERESPONSE,
  __module__ = 'challenge_action_pb2'
  # @@protoc_insertion_point(class_scope:ChallengeAction.ChallengeResponse)
  ))
_sym_db.RegisterMessage(ChallengeResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n com.google.android.finsky.protosB\017ChallengeAction'))
# @@protoc_insertion_point(module_scope)
