# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consume_purchase_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import library_update_proto_pb2 as library__update__proto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='consume_purchase_response.proto',
  package='ConsumePurchaseResponse',
  syntax='proto2',
  serialized_pb=_b('\n\x1f\x63onsume_purchase_response.proto\x12\x17\x43onsumePurchaseResponse\x1a\x1alibrary_update_proto.proto\"c\n\x17\x43onsumePurchaseResponse\x12\x38\n\rlibraryUpdate\x18\x01 \x01(\x0b\x32!.LibraryUpdateProto.LibraryUpdate\x12\x0e\n\x06status\x18\x02 \x01(\x05\x42=\n com.google.android.finsky.protosB\x17\x43onsumePurchaseResponseP\x01')
  ,
  dependencies=[library__update__proto__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONSUMEPURCHASERESPONSE = _descriptor.Descriptor(
  name='ConsumePurchaseResponse',
  full_name='ConsumePurchaseResponse.ConsumePurchaseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='libraryUpdate', full_name='ConsumePurchaseResponse.ConsumePurchaseResponse.libraryUpdate', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='ConsumePurchaseResponse.ConsumePurchaseResponse.status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=187,
)

_CONSUMEPURCHASERESPONSE.fields_by_name['libraryUpdate'].message_type = library__update__proto__pb2._LIBRARYUPDATE
DESCRIPTOR.message_types_by_name['ConsumePurchaseResponse'] = _CONSUMEPURCHASERESPONSE

ConsumePurchaseResponse = _reflection.GeneratedProtocolMessageType('ConsumePurchaseResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONSUMEPURCHASERESPONSE,
  __module__ = 'consume_purchase_response_pb2'
  # @@protoc_insertion_point(class_scope:ConsumePurchaseResponse.ConsumePurchaseResponse)
  ))
_sym_db.RegisterMessage(ConsumePurchaseResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n com.google.android.finsky.protosB\027ConsumePurchaseResponseP\001'))
# @@protoc_insertion_point(module_scope)
