# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: content_flagging.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='content_flagging.proto',
  package='ContentFlagging',
  syntax='proto2',
  serialized_pb=_b('\n\x16\x63ontent_flagging.proto\x12\x0f\x43ontentFlagging\"\x15\n\x13\x46lagContentResponseB3\n com.google.android.finsky.protosB\x0f\x43ontentFlagging')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FLAGCONTENTRESPONSE = _descriptor.Descriptor(
  name='FlagContentResponse',
  full_name='ContentFlagging.FlagContentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=64,
)

DESCRIPTOR.message_types_by_name['FlagContentResponse'] = _FLAGCONTENTRESPONSE

FlagContentResponse = _reflection.GeneratedProtocolMessageType('FlagContentResponse', (_message.Message,), dict(
  DESCRIPTOR = _FLAGCONTENTRESPONSE,
  __module__ = 'content_flagging_pb2'
  # @@protoc_insertion_point(class_scope:ContentFlagging.FlagContentResponse)
  ))
_sym_db.RegisterMessage(FlagContentResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n com.google.android.finsky.protosB\017ContentFlagging'))
# @@protoc_insertion_point(module_scope)
