# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dcb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import legal_message_outer_class_pb2 as legal__message__outer__class__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dcb.proto',
  package='Dcb',
  syntax='proto2',
  serialized_pb=_b('\n\tdcb.proto\x12\x03\x44\x63\x62\x1a\x1flegal_message_outer_class.proto\"\x85\x01\n\x18\x44\x63\x62VerifyAssociationForm\x12\x16\n\x0esmsPhoneNumber\x18\x01 \x01(\t\x12\x12\n\nsmsMessage\x18\x02 \x01(\t\x12=\n\x0frequiredMessage\x18\x03 \x01(\x0b\x32$.LegalMessageOuterClass.LegalMessage\"5\n\x1d\x44\x63\x62VerifyAssociationFormValue\x12\x14\n\x0clegalDocData\x18\x01 \x01(\tB]\nVcom.google.commerce.payments.orchestration.proto.ui.common.components.instrument.typesB\x03\x44\x63\x62')
  ,
  dependencies=[legal__message__outer__class__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCBVERIFYASSOCIATIONFORM = _descriptor.Descriptor(
  name='DcbVerifyAssociationForm',
  full_name='Dcb.DcbVerifyAssociationForm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='smsPhoneNumber', full_name='Dcb.DcbVerifyAssociationForm.smsPhoneNumber', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='smsMessage', full_name='Dcb.DcbVerifyAssociationForm.smsMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requiredMessage', full_name='Dcb.DcbVerifyAssociationForm.requiredMessage', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=185,
)


_DCBVERIFYASSOCIATIONFORMVALUE = _descriptor.Descriptor(
  name='DcbVerifyAssociationFormValue',
  full_name='Dcb.DcbVerifyAssociationFormValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='legalDocData', full_name='Dcb.DcbVerifyAssociationFormValue.legalDocData', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=240,
)

_DCBVERIFYASSOCIATIONFORM.fields_by_name['requiredMessage'].message_type = legal__message__outer__class__pb2._LEGALMESSAGE
DESCRIPTOR.message_types_by_name['DcbVerifyAssociationForm'] = _DCBVERIFYASSOCIATIONFORM
DESCRIPTOR.message_types_by_name['DcbVerifyAssociationFormValue'] = _DCBVERIFYASSOCIATIONFORMVALUE

DcbVerifyAssociationForm = _reflection.GeneratedProtocolMessageType('DcbVerifyAssociationForm', (_message.Message,), dict(
  DESCRIPTOR = _DCBVERIFYASSOCIATIONFORM,
  __module__ = 'dcb_pb2'
  # @@protoc_insertion_point(class_scope:Dcb.DcbVerifyAssociationForm)
  ))
_sym_db.RegisterMessage(DcbVerifyAssociationForm)

DcbVerifyAssociationFormValue = _reflection.GeneratedProtocolMessageType('DcbVerifyAssociationFormValue', (_message.Message,), dict(
  DESCRIPTOR = _DCBVERIFYASSOCIATIONFORMVALUE,
  __module__ = 'dcb_pb2'
  # @@protoc_insertion_point(class_scope:Dcb.DcbVerifyAssociationFormValue)
  ))
_sym_db.RegisterMessage(DcbVerifyAssociationFormValue)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\nVcom.google.commerce.payments.orchestration.proto.ui.common.components.instrument.typesB\003Dcb'))
# @@protoc_insertion_point(module_scope)
