# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debug_settings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='debug_settings.proto',
  package='DebugSettings',
  syntax='proto2',
  serialized_pb=_b('\n\x14\x64\x65\x62ug_settings.proto\x12\rDebugSettings\"R\n\x15\x44\x65\x62ugSettingsResponse\x12\x1b\n\x13playCountryOverride\x18\x01 \x01(\t\x12\x1c\n\x14playCountryDebugInfo\x18\x02 \x01(\tB1\n com.google.android.finsky.protosB\rDebugSettings')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DEBUGSETTINGSRESPONSE = _descriptor.Descriptor(
  name='DebugSettingsResponse',
  full_name='DebugSettings.DebugSettingsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playCountryOverride', full_name='DebugSettings.DebugSettingsResponse.playCountryOverride', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playCountryDebugInfo', full_name='DebugSettings.DebugSettingsResponse.playCountryDebugInfo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['DebugSettingsResponse'] = _DEBUGSETTINGSRESPONSE

DebugSettingsResponse = _reflection.GeneratedProtocolMessageType('DebugSettingsResponse', (_message.Message,), dict(
  DESCRIPTOR = _DEBUGSETTINGSRESPONSE,
  __module__ = 'debug_settings_pb2'
  # @@protoc_insertion_point(class_scope:DebugSettings.DebugSettingsResponse)
  ))
_sym_db.RegisterMessage(DebugSettingsResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n com.google.android.finsky.protosB\rDebugSettings'))
# @@protoc_insertion_point(module_scope)
