# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: delivery.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import android_app_delivery_pb2 as android__app__delivery__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='delivery.proto',
  package='Delivery',
  syntax='proto2',
  serialized_pb=_b('\n\x0e\x64\x65livery.proto\x12\x08\x44\x65livery\x1a\x1a\x61ndroid_app_delivery.proto\"g\n\x10\x44\x65liveryResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x43\n\x0f\x61ppDeliveryData\x18\x02 \x01(\x0b\x32*.AndroidAppDelivery.AndroidAppDeliveryDataB,\n com.google.android.finsky.protosB\x08\x44\x65livery')
  ,
  dependencies=[android__app__delivery__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DELIVERYRESPONSE = _descriptor.Descriptor(
  name='DeliveryResponse',
  full_name='Delivery.DeliveryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Delivery.DeliveryResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='appDeliveryData', full_name='Delivery.DeliveryResponse.appDeliveryData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=159,
)

_DELIVERYRESPONSE.fields_by_name['appDeliveryData'].message_type = android__app__delivery__pb2._ANDROIDAPPDELIVERYDATA
DESCRIPTOR.message_types_by_name['DeliveryResponse'] = _DELIVERYRESPONSE

DeliveryResponse = _reflection.GeneratedProtocolMessageType('DeliveryResponse', (_message.Message,), dict(
  DESCRIPTOR = _DELIVERYRESPONSE,
  __module__ = 'delivery_pb2'
  # @@protoc_insertion_point(class_scope:Delivery.DeliveryResponse)
  ))
_sym_db.RegisterMessage(DeliveryResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n com.google.android.finsky.protosB\010Delivery'))
# @@protoc_insertion_point(module_scope)
