# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: doc_annotations.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import resolve_link_pb2 as resolve__link__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='doc_annotations.proto',
  package='DocAnnotations',
  syntax='proto2',
  serialized_pb=_b('\n\x15\x64oc_annotations.proto\x12\x0e\x44ocAnnotations\x1a\x12resolve_link.proto\x1a\x0c\x63ommon.proto\"\x8a\x01\n\x16PurchaseHistoryDetails\x12\x1d\n\x15purchaseTimestampMsec\x18\x02 \x01(\x03\x12\x1b\n\x13purchaseDetailsHtml\x18\x03 \x01(\t\x12\x1c\n\x05offer\x18\x05 \x01(\x0b\x32\r.Common.Offer\x12\x16\n\x0epurchaseStatus\x18\x06 \x01(\t\"\xa3\x01\n\x05\x42\x61\x64ge\x12\r\n\x05title\x18\x01 \x01(\t\x12\x1c\n\x05image\x18\x02 \x03(\x0b\x32\r.Common.Image\x12\x11\n\tbrowseUrl\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x1a\n\x12textInTitleSection\x18\x05 \x01(\t\x12)\n\x12\x65xpandedBadgeImage\x18\x06 \x01(\x0b\x32\r.Common.Image\"^\n\x0fSectionMetadata\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x0f\n\x07listUrl\x18\x02 \x01(\t\x12\x11\n\tbrowseUrl\x18\x03 \x01(\t\x12\x17\n\x0f\x64\x65scriptionHtml\x18\x04 \x01(\t\"y\n\x0bPromotedDoc\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08subtitle\x18\x02 \x01(\t\x12\x1c\n\x05image\x18\x03 \x03(\x0b\x32\r.Common.Image\x12\x17\n\x0f\x64\x65scriptionHtml\x18\x04 \x01(\t\x12\x12\n\ndetailsUrl\x18\x05 \x01(\t\"X\n\x04Link\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12/\n\x0cresolvedLink\x18\x02 \x01(\x0b\x32\x19.ResolveLink.ResolvedLink\x12\x12\n\nuriBackend\x18\x03 \x01(\x05\"#\n\x07Warning\x12\x18\n\x10localizedMessage\x18\x01 \x01(\t\"c\n\x0e\x42\x61\x64geContainer\x12\r\n\x05title\x18\x01 \x01(\t\x12\x1c\n\x05image\x18\x02 \x03(\x0b\x32\r.Common.Image\x12$\n\x05\x62\x61\x64ge\x18\x03 \x03(\x0b\x32\x15.DocAnnotations.BadgeB2\n com.google.android.finsky.protosB\x0e\x44ocAnnotations')
  ,
  dependencies=[resolve__link__pb2.DESCRIPTOR,common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PURCHASEHISTORYDETAILS = _descriptor.Descriptor(
  name='PurchaseHistoryDetails',
  full_name='DocAnnotations.PurchaseHistoryDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='purchaseTimestampMsec', full_name='DocAnnotations.PurchaseHistoryDetails.purchaseTimestampMsec', index=0,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='purchaseDetailsHtml', full_name='DocAnnotations.PurchaseHistoryDetails.purchaseDetailsHtml', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offer', full_name='DocAnnotations.PurchaseHistoryDetails.offer', index=2,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='purchaseStatus', full_name='DocAnnotations.PurchaseHistoryDetails.purchaseStatus', index=3,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=214,
)


_BADGE = _descriptor.Descriptor(
  name='Badge',
  full_name='DocAnnotations.Badge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='DocAnnotations.Badge.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='DocAnnotations.Badge.image', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='browseUrl', full_name='DocAnnotations.Badge.browseUrl', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='DocAnnotations.Badge.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='textInTitleSection', full_name='DocAnnotations.Badge.textInTitleSection', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expandedBadgeImage', full_name='DocAnnotations.Badge.expandedBadgeImage', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=380,
)


_SECTIONMETADATA = _descriptor.Descriptor(
  name='SectionMetadata',
  full_name='DocAnnotations.SectionMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='DocAnnotations.SectionMetadata.header', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='listUrl', full_name='DocAnnotations.SectionMetadata.listUrl', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='browseUrl', full_name='DocAnnotations.SectionMetadata.browseUrl', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='descriptionHtml', full_name='DocAnnotations.SectionMetadata.descriptionHtml', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=476,
)


_PROMOTEDDOC = _descriptor.Descriptor(
  name='PromotedDoc',
  full_name='DocAnnotations.PromotedDoc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='DocAnnotations.PromotedDoc.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subtitle', full_name='DocAnnotations.PromotedDoc.subtitle', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='DocAnnotations.PromotedDoc.image', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='descriptionHtml', full_name='DocAnnotations.PromotedDoc.descriptionHtml', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='detailsUrl', full_name='DocAnnotations.PromotedDoc.detailsUrl', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=478,
  serialized_end=599,
)


_LINK = _descriptor.Descriptor(
  name='Link',
  full_name='DocAnnotations.Link',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='DocAnnotations.Link.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resolvedLink', full_name='DocAnnotations.Link.resolvedLink', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uriBackend', full_name='DocAnnotations.Link.uriBackend', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=601,
  serialized_end=689,
)


_WARNING = _descriptor.Descriptor(
  name='Warning',
  full_name='DocAnnotations.Warning',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='localizedMessage', full_name='DocAnnotations.Warning.localizedMessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=691,
  serialized_end=726,
)


_BADGECONTAINER = _descriptor.Descriptor(
  name='BadgeContainer',
  full_name='DocAnnotations.BadgeContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='DocAnnotations.BadgeContainer.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='DocAnnotations.BadgeContainer.image', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='badge', full_name='DocAnnotations.BadgeContainer.badge', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=728,
  serialized_end=827,
)

_PURCHASEHISTORYDETAILS.fields_by_name['offer'].message_type = common__pb2._OFFER
_BADGE.fields_by_name['image'].message_type = common__pb2._IMAGE
_BADGE.fields_by_name['expandedBadgeImage'].message_type = common__pb2._IMAGE
_PROMOTEDDOC.fields_by_name['image'].message_type = common__pb2._IMAGE
_LINK.fields_by_name['resolvedLink'].message_type = resolve__link__pb2._RESOLVEDLINK
_BADGECONTAINER.fields_by_name['image'].message_type = common__pb2._IMAGE
_BADGECONTAINER.fields_by_name['badge'].message_type = _BADGE
DESCRIPTOR.message_types_by_name['PurchaseHistoryDetails'] = _PURCHASEHISTORYDETAILS
DESCRIPTOR.message_types_by_name['Badge'] = _BADGE
DESCRIPTOR.message_types_by_name['SectionMetadata'] = _SECTIONMETADATA
DESCRIPTOR.message_types_by_name['PromotedDoc'] = _PROMOTEDDOC
DESCRIPTOR.message_types_by_name['Link'] = _LINK
DESCRIPTOR.message_types_by_name['Warning'] = _WARNING
DESCRIPTOR.message_types_by_name['BadgeContainer'] = _BADGECONTAINER

PurchaseHistoryDetails = _reflection.GeneratedProtocolMessageType('PurchaseHistoryDetails', (_message.Message,), dict(
  DESCRIPTOR = _PURCHASEHISTORYDETAILS,
  __module__ = 'doc_annotations_pb2'
  # @@protoc_insertion_point(class_scope:DocAnnotations.PurchaseHistoryDetails)
  ))
_sym_db.RegisterMessage(PurchaseHistoryDetails)

Badge = _reflection.GeneratedProtocolMessageType('Badge', (_message.Message,), dict(
  DESCRIPTOR = _BADGE,
  __module__ = 'doc_annotations_pb2'
  # @@protoc_insertion_point(class_scope:DocAnnotations.Badge)
  ))
_sym_db.RegisterMessage(Badge)

SectionMetadata = _reflection.GeneratedProtocolMessageType('SectionMetadata', (_message.Message,), dict(
  DESCRIPTOR = _SECTIONMETADATA,
  __module__ = 'doc_annotations_pb2'
  # @@protoc_insertion_point(class_scope:DocAnnotations.SectionMetadata)
  ))
_sym_db.RegisterMessage(SectionMetadata)

PromotedDoc = _reflection.GeneratedProtocolMessageType('PromotedDoc', (_message.Message,), dict(
  DESCRIPTOR = _PROMOTEDDOC,
  __module__ = 'doc_annotations_pb2'
  # @@protoc_insertion_point(class_scope:DocAnnotations.PromotedDoc)
  ))
_sym_db.RegisterMessage(PromotedDoc)

Link = _reflection.GeneratedProtocolMessageType('Link', (_message.Message,), dict(
  DESCRIPTOR = _LINK,
  __module__ = 'doc_annotations_pb2'
  # @@protoc_insertion_point(class_scope:DocAnnotations.Link)
  ))
_sym_db.RegisterMessage(Link)

Warning = _reflection.GeneratedProtocolMessageType('Warning', (_message.Message,), dict(
  DESCRIPTOR = _WARNING,
  __module__ = 'doc_annotations_pb2'
  # @@protoc_insertion_point(class_scope:DocAnnotations.Warning)
  ))
_sym_db.RegisterMessage(Warning)

BadgeContainer = _reflection.GeneratedProtocolMessageType('BadgeContainer', (_message.Message,), dict(
  DESCRIPTOR = _BADGECONTAINER,
  __module__ = 'doc_annotations_pb2'
  # @@protoc_insertion_point(class_scope:DocAnnotations.BadgeContainer)
  ))
_sym_db.RegisterMessage(BadgeContainer)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n com.google.android.finsky.protosB\016DocAnnotations'))
# @@protoc_insertion_point(module_scope)
