# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: info_message_outer_class.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='info_message_outer_class.proto',
  package='InfoMessageOuterClass',
  syntax='proto2',
  serialized_pb=_b('\n\x1einfo_message_outer_class.proto\x12\x15InfoMessageOuterClass\"v\n\x0bInfoMessage\x12\x13\n\x0bmessageHtml\x18\x01 \x01(\t\x12\x1b\n\x13\x64\x65tailedMessageHtml\x18\x02 \x01(\t\x12 \n\x18showDetailedMessageLabel\x18\x03 \x01(\t\x12\x13\n\x0buiReference\x18\x04 \x01(\x05\x42[\nBcom.google.commerce.payments.orchestration.proto.ui.common.genericB\x15InfoMessageOuterClass')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INFOMESSAGE = _descriptor.Descriptor(
  name='InfoMessage',
  full_name='InfoMessageOuterClass.InfoMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageHtml', full_name='InfoMessageOuterClass.InfoMessage.messageHtml', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='detailedMessageHtml', full_name='InfoMessageOuterClass.InfoMessage.detailedMessageHtml', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='showDetailedMessageLabel', full_name='InfoMessageOuterClass.InfoMessage.showDetailedMessageLabel', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uiReference', full_name='InfoMessageOuterClass.InfoMessage.uiReference', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=175,
)

DESCRIPTOR.message_types_by_name['InfoMessage'] = _INFOMESSAGE

InfoMessage = _reflection.GeneratedProtocolMessageType('InfoMessage', (_message.Message,), dict(
  DESCRIPTOR = _INFOMESSAGE,
  __module__ = 'info_message_outer_class_pb2'
  # @@protoc_insertion_point(class_scope:InfoMessageOuterClass.InfoMessage)
  ))
_sym_db.RegisterMessage(InfoMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\nBcom.google.commerce.payments.orchestration.proto.ui.common.genericB\025InfoMessageOuterClass'))
# @@protoc_insertion_point(module_scope)
