# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: legal_message_set_outer_class.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import legal_message_outer_class_pb2 as legal__message__outer__class__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='legal_message_set_outer_class.proto',
  package='LegalMessageSetOuterClass',
  syntax='proto2',
  serialized_pb=_b('\n#legal_message_set_outer_class.proto\x12\x19LegalMessageSetOuterClass\x1a\x1flegal_message_outer_class.proto\"_\n\x15LegalMessageByCountry\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x35\n\x07message\x18\x02 \x01(\x0b\x32$.LegalMessageOuterClass.LegalMessage\"\x9b\x01\n\x0fLegalMessageSet\x12<\n\x0e\x64\x65\x66\x61ultMessage\x18\x01 \x01(\x0b\x32$.LegalMessageOuterClass.LegalMessage\x12J\n\x10messageByCountry\x18\x02 \x03(\x0b\x32\x30.LegalMessageSetOuterClass.LegalMessageByCountryBh\nKcom.google.commerce.payments.orchestration.proto.ui.common.components.legalB\x19LegalMessageSetOuterClass')
  ,
  dependencies=[legal__message__outer__class__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LEGALMESSAGEBYCOUNTRY = _descriptor.Descriptor(
  name='LegalMessageByCountry',
  full_name='LegalMessageSetOuterClass.LegalMessageByCountry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='country', full_name='LegalMessageSetOuterClass.LegalMessageByCountry.country', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='LegalMessageSetOuterClass.LegalMessageByCountry.message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=194,
)


_LEGALMESSAGESET = _descriptor.Descriptor(
  name='LegalMessageSet',
  full_name='LegalMessageSetOuterClass.LegalMessageSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='defaultMessage', full_name='LegalMessageSetOuterClass.LegalMessageSet.defaultMessage', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='messageByCountry', full_name='LegalMessageSetOuterClass.LegalMessageSet.messageByCountry', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=352,
)

_LEGALMESSAGEBYCOUNTRY.fields_by_name['message'].message_type = legal__message__outer__class__pb2._LEGALMESSAGE
_LEGALMESSAGESET.fields_by_name['defaultMessage'].message_type = legal__message__outer__class__pb2._LEGALMESSAGE
_LEGALMESSAGESET.fields_by_name['messageByCountry'].message_type = _LEGALMESSAGEBYCOUNTRY
DESCRIPTOR.message_types_by_name['LegalMessageByCountry'] = _LEGALMESSAGEBYCOUNTRY
DESCRIPTOR.message_types_by_name['LegalMessageSet'] = _LEGALMESSAGESET

LegalMessageByCountry = _reflection.GeneratedProtocolMessageType('LegalMessageByCountry', (_message.Message,), dict(
  DESCRIPTOR = _LEGALMESSAGEBYCOUNTRY,
  __module__ = 'legal_message_set_outer_class_pb2'
  # @@protoc_insertion_point(class_scope:LegalMessageSetOuterClass.LegalMessageByCountry)
  ))
_sym_db.RegisterMessage(LegalMessageByCountry)

LegalMessageSet = _reflection.GeneratedProtocolMessageType('LegalMessageSet', (_message.Message,), dict(
  DESCRIPTOR = _LEGALMESSAGESET,
  __module__ = 'legal_message_set_outer_class_pb2'
  # @@protoc_insertion_point(class_scope:LegalMessageSetOuterClass.LegalMessageSet)
  ))
_sym_db.RegisterMessage(LegalMessageSet)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\nKcom.google.commerce.payments.orchestration.proto.ui.common.components.legalB\031LegalMessageSetOuterClass'))
# @@protoc_insertion_point(module_scope)
