# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: music_doc_details.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import doc_annotations_pb2 as doc__annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='music_doc_details.proto',
  package='MusicDocDetails',
  syntax='proto2',
  serialized_pb=_b('\n\x17music_doc_details.proto\x12\x0fMusicDocDetails\x1a\x15\x64oc_annotations.proto\"b\n\x13\x41rtistExternalLinks\x12\x12\n\nwebsiteUrl\x18\x01 \x03(\t\x12\x1c\n\x14googlePlusProfileUrl\x18\x02 \x01(\t\x12\x19\n\x11youtubeChannelUrl\x18\x03 \x01(\t\"\x83\x01\n\x0c\x41lbumDetails\x12\x0c\n\x04name\x18\x01 \x01(\t\x12.\n\x07\x64\x65tails\x18\x02 \x01(\x0b\x32\x1d.MusicDocDetails.MusicDetails\x12\x35\n\rdisplayArtist\x18\x03 \x01(\x0b\x32\x1e.MusicDocDetails.ArtistDetails\"\xe4\x01\n\x0bSongDetails\x12\x0c\n\x04name\x18\x01 \x01(\t\x12.\n\x07\x64\x65tails\x18\x02 \x01(\x0b\x32\x1d.MusicDocDetails.MusicDetails\x12\x11\n\talbumName\x18\x03 \x01(\t\x12\x13\n\x0btrackNumber\x18\x04 \x01(\x05\x12\x12\n\npreviewUrl\x18\x05 \x01(\t\x12\x35\n\rdisplayArtist\x18\x06 \x01(\x0b\x32\x1e.MusicDocDetails.ArtistDetails\x12$\n\x05\x62\x61\x64ge\x18\x07 \x01(\x0b\x32\x15.DocAnnotations.Badge\"n\n\rArtistDetails\x12\x12\n\ndetailsUrl\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12;\n\rexternalLinks\x18\x03 \x01(\x0b\x32$.MusicDocDetails.ArtistExternalLinks\"\xcb\x01\n\x0cMusicDetails\x12\x11\n\tcensoring\x18\x01 \x01(\x05\x12\x13\n\x0b\x64urationSec\x18\x02 \x01(\x05\x12\x1b\n\x13originalReleaseDate\x18\x03 \x01(\t\x12\r\n\x05label\x18\x04 \x01(\t\x12.\n\x06\x61rtist\x18\x05 \x03(\x0b\x32\x1e.MusicDocDetails.ArtistDetails\x12\r\n\x05genre\x18\x06 \x03(\t\x12\x13\n\x0breleaseDate\x18\x07 \x01(\t\x12\x13\n\x0breleaseType\x18\x08 \x03(\x05\x42\x33\n com.google.android.finsky.protosB\x0fMusicDocDetails')
  ,
  dependencies=[doc__annotations__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ARTISTEXTERNALLINKS = _descriptor.Descriptor(
  name='ArtistExternalLinks',
  full_name='MusicDocDetails.ArtistExternalLinks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='websiteUrl', full_name='MusicDocDetails.ArtistExternalLinks.websiteUrl', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='googlePlusProfileUrl', full_name='MusicDocDetails.ArtistExternalLinks.googlePlusProfileUrl', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='youtubeChannelUrl', full_name='MusicDocDetails.ArtistExternalLinks.youtubeChannelUrl', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=165,
)


_ALBUMDETAILS = _descriptor.Descriptor(
  name='AlbumDetails',
  full_name='MusicDocDetails.AlbumDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MusicDocDetails.AlbumDetails.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='details', full_name='MusicDocDetails.AlbumDetails.details', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='displayArtist', full_name='MusicDocDetails.AlbumDetails.displayArtist', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=299,
)


_SONGDETAILS = _descriptor.Descriptor(
  name='SongDetails',
  full_name='MusicDocDetails.SongDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MusicDocDetails.SongDetails.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='details', full_name='MusicDocDetails.SongDetails.details', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='albumName', full_name='MusicDocDetails.SongDetails.albumName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trackNumber', full_name='MusicDocDetails.SongDetails.trackNumber', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='previewUrl', full_name='MusicDocDetails.SongDetails.previewUrl', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='displayArtist', full_name='MusicDocDetails.SongDetails.displayArtist', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='badge', full_name='MusicDocDetails.SongDetails.badge', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=530,
)


_ARTISTDETAILS = _descriptor.Descriptor(
  name='ArtistDetails',
  full_name='MusicDocDetails.ArtistDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detailsUrl', full_name='MusicDocDetails.ArtistDetails.detailsUrl', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='MusicDocDetails.ArtistDetails.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='externalLinks', full_name='MusicDocDetails.ArtistDetails.externalLinks', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=642,
)


_MUSICDETAILS = _descriptor.Descriptor(
  name='MusicDetails',
  full_name='MusicDocDetails.MusicDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='censoring', full_name='MusicDocDetails.MusicDetails.censoring', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='durationSec', full_name='MusicDocDetails.MusicDetails.durationSec', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='originalReleaseDate', full_name='MusicDocDetails.MusicDetails.originalReleaseDate', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='MusicDocDetails.MusicDetails.label', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='artist', full_name='MusicDocDetails.MusicDetails.artist', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='genre', full_name='MusicDocDetails.MusicDetails.genre', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='releaseDate', full_name='MusicDocDetails.MusicDetails.releaseDate', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='releaseType', full_name='MusicDocDetails.MusicDetails.releaseType', index=7,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=645,
  serialized_end=848,
)

_ALBUMDETAILS.fields_by_name['details'].message_type = _MUSICDETAILS
_ALBUMDETAILS.fields_by_name['displayArtist'].message_type = _ARTISTDETAILS
_SONGDETAILS.fields_by_name['details'].message_type = _MUSICDETAILS
_SONGDETAILS.fields_by_name['displayArtist'].message_type = _ARTISTDETAILS
_SONGDETAILS.fields_by_name['badge'].message_type = doc__annotations__pb2._BADGE
_ARTISTDETAILS.fields_by_name['externalLinks'].message_type = _ARTISTEXTERNALLINKS
_MUSICDETAILS.fields_by_name['artist'].message_type = _ARTISTDETAILS
DESCRIPTOR.message_types_by_name['ArtistExternalLinks'] = _ARTISTEXTERNALLINKS
DESCRIPTOR.message_types_by_name['AlbumDetails'] = _ALBUMDETAILS
DESCRIPTOR.message_types_by_name['SongDetails'] = _SONGDETAILS
DESCRIPTOR.message_types_by_name['ArtistDetails'] = _ARTISTDETAILS
DESCRIPTOR.message_types_by_name['MusicDetails'] = _MUSICDETAILS

ArtistExternalLinks = _reflection.GeneratedProtocolMessageType('ArtistExternalLinks', (_message.Message,), dict(
  DESCRIPTOR = _ARTISTEXTERNALLINKS,
  __module__ = 'music_doc_details_pb2'
  # @@protoc_insertion_point(class_scope:MusicDocDetails.ArtistExternalLinks)
  ))
_sym_db.RegisterMessage(ArtistExternalLinks)

AlbumDetails = _reflection.GeneratedProtocolMessageType('AlbumDetails', (_message.Message,), dict(
  DESCRIPTOR = _ALBUMDETAILS,
  __module__ = 'music_doc_details_pb2'
  # @@protoc_insertion_point(class_scope:MusicDocDetails.AlbumDetails)
  ))
_sym_db.RegisterMessage(AlbumDetails)

SongDetails = _reflection.GeneratedProtocolMessageType('SongDetails', (_message.Message,), dict(
  DESCRIPTOR = _SONGDETAILS,
  __module__ = 'music_doc_details_pb2'
  # @@protoc_insertion_point(class_scope:MusicDocDetails.SongDetails)
  ))
_sym_db.RegisterMessage(SongDetails)

ArtistDetails = _reflection.GeneratedProtocolMessageType('ArtistDetails', (_message.Message,), dict(
  DESCRIPTOR = _ARTISTDETAILS,
  __module__ = 'music_doc_details_pb2'
  # @@protoc_insertion_point(class_scope:MusicDocDetails.ArtistDetails)
  ))
_sym_db.RegisterMessage(ArtistDetails)

MusicDetails = _reflection.GeneratedProtocolMessageType('MusicDetails', (_message.Message,), dict(
  DESCRIPTOR = _MUSICDETAILS,
  __module__ = 'music_doc_details_pb2'
  # @@protoc_insertion_point(class_scope:MusicDocDetails.MusicDetails)
  ))
_sym_db.RegisterMessage(MusicDetails)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n com.google.android.finsky.protosB\017MusicDocDetails'))
# @@protoc_insertion_point(module_scope)
