# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: play_plus_profile.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import document_pb2 as document__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='play_plus_profile.proto',
  package='PlayPlusProfile',
  syntax='proto2',
  serialized_pb=_b('\n\x17play_plus_profile.proto\x12\x0fPlayPlusProfile\x1a\x0e\x64ocument.proto\"[\n\x17PlayPlusProfileResponse\x12+\n\x0buserProfile\x18\x01 \x01(\x0b\x32\x16.Document.PlayDocument\x12\x13\n\x0bisGplusUser\x18\x02 \x01(\x08\x42\x33\n com.google.android.finsky.protosB\x0fPlayPlusProfile')
  ,
  dependencies=[document__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PLAYPLUSPROFILERESPONSE = _descriptor.Descriptor(
  name='PlayPlusProfileResponse',
  full_name='PlayPlusProfile.PlayPlusProfileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userProfile', full_name='PlayPlusProfile.PlayPlusProfileResponse.userProfile', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isGplusUser', full_name='PlayPlusProfile.PlayPlusProfileResponse.isGplusUser', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=151,
)

_PLAYPLUSPROFILERESPONSE.fields_by_name['userProfile'].message_type = document__pb2._PLAYDOCUMENT
DESCRIPTOR.message_types_by_name['PlayPlusProfileResponse'] = _PLAYPLUSPROFILERESPONSE

PlayPlusProfileResponse = _reflection.GeneratedProtocolMessageType('PlayPlusProfileResponse', (_message.Message,), dict(
  DESCRIPTOR = _PLAYPLUSPROFILERESPONSE,
  __module__ = 'play_plus_profile_pb2'
  # @@protoc_insertion_point(class_scope:PlayPlusProfile.PlayPlusProfileResponse)
  ))
_sym_db.RegisterMessage(PlayPlusProfileResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n com.google.android.finsky.protosB\017PlayPlusProfile'))
# @@protoc_insertion_point(module_scope)
