# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: postaladdress.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='postaladdress.proto',
  package='Postaladdress',
  syntax='proto2',
  serialized_pb=_b('\n\x13postaladdress.proto\x12\rPostaladdress\"\x8f\x04\n\rPostalAddress\x12\x17\n\x0f\x63ountryNameCode\x18\x01 \x01(\t\x12\x13\n\x0b\x63ountryName\x18\x02 \x01(\t\x12\x1e\n\x16\x61\x64ministrativeAreaName\x18\x03 \x01(\t\x12!\n\x19subAdministrativeAreaName\x18\x04 \x01(\t\x12\x14\n\x0clocalityName\x18\x05 \x01(\t\x12\x18\n\x10thoroughfareName\x18\x06 \x01(\t\x12\x1a\n\x12thoroughfareNumber\x18\x0b \x01(\t\x12\x18\n\x10postalCodeNumber\x18\x0c \x01(\t\x12!\n\x19postalCodeNumberExtension\x18\r \x01(\t\x12\x13\n\x0b\x61\x64\x64ressLine\x18\x0e \x03(\t\x12\x13\n\x0bpremiseName\x18\x0f \x01(\t\x12\x16\n\x0esubPremiseName\x18\x10 \x01(\t\x12\x1d\n\x15\x64\x65pendentLocalityName\x18\x11 \x01(\t\x12!\n\x19\x64\x65pendentThoroughfareName\x18\x15 \x01(\t\x12\x14\n\x0clanguageCode\x18\x1a \x01(\t\x12\x10\n\x08\x66irmName\x18\x1b \x01(\t\x12\x15\n\rrecipientName\x18\x1c \x01(\t\x12\x13\n\x0bsortingCode\x18\x1d \x01(\t\x12\x15\n\rpostBoxNumber\x18\x1e \x01(\t\x12\x15\n\x0c\x65mailAddress\x18\xfe\x08 \x01(\tB,\n\x1b\x63om.google.location.countryB\rPostaladdress')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POSTALADDRESS = _descriptor.Descriptor(
  name='PostalAddress',
  full_name='Postaladdress.PostalAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='countryNameCode', full_name='Postaladdress.PostalAddress.countryNameCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='countryName', full_name='Postaladdress.PostalAddress.countryName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='administrativeAreaName', full_name='Postaladdress.PostalAddress.administrativeAreaName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subAdministrativeAreaName', full_name='Postaladdress.PostalAddress.subAdministrativeAreaName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='localityName', full_name='Postaladdress.PostalAddress.localityName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='thoroughfareName', full_name='Postaladdress.PostalAddress.thoroughfareName', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='thoroughfareNumber', full_name='Postaladdress.PostalAddress.thoroughfareNumber', index=6,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='postalCodeNumber', full_name='Postaladdress.PostalAddress.postalCodeNumber', index=7,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='postalCodeNumberExtension', full_name='Postaladdress.PostalAddress.postalCodeNumberExtension', index=8,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='addressLine', full_name='Postaladdress.PostalAddress.addressLine', index=9,
      number=14, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='premiseName', full_name='Postaladdress.PostalAddress.premiseName', index=10,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subPremiseName', full_name='Postaladdress.PostalAddress.subPremiseName', index=11,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dependentLocalityName', full_name='Postaladdress.PostalAddress.dependentLocalityName', index=12,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dependentThoroughfareName', full_name='Postaladdress.PostalAddress.dependentThoroughfareName', index=13,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='languageCode', full_name='Postaladdress.PostalAddress.languageCode', index=14,
      number=26, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='firmName', full_name='Postaladdress.PostalAddress.firmName', index=15,
      number=27, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recipientName', full_name='Postaladdress.PostalAddress.recipientName', index=16,
      number=28, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sortingCode', full_name='Postaladdress.PostalAddress.sortingCode', index=17,
      number=29, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='postBoxNumber', full_name='Postaladdress.PostalAddress.postBoxNumber', index=18,
      number=30, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='emailAddress', full_name='Postaladdress.PostalAddress.emailAddress', index=19,
      number=1150, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=566,
)

DESCRIPTOR.message_types_by_name['PostalAddress'] = _POSTALADDRESS

PostalAddress = _reflection.GeneratedProtocolMessageType('PostalAddress', (_message.Message,), dict(
  DESCRIPTOR = _POSTALADDRESS,
  __module__ = 'postaladdress_pb2'
  # @@protoc_insertion_point(class_scope:Postaladdress.PostalAddress)
  ))
_sym_db.RegisterMessage(PostalAddress)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033com.google.location.countryB\rPostaladdress'))
# @@protoc_insertion_point(module_scope)
