# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rate_suggested_content_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rate_suggested_content_response.proto',
  package='RateSuggestedContentResponse',
  syntax='proto2',
  serialized_pb=_b('\n%rate_suggested_content_response.proto\x12\x1cRateSuggestedContentResponse\"\x1e\n\x1cRateSuggestedContentResponseBB\n com.google.android.finsky.protosB\x1cRateSuggestedContentResponseP\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RATESUGGESTEDCONTENTRESPONSE = _descriptor.Descriptor(
  name='RateSuggestedContentResponse',
  full_name='RateSuggestedContentResponse.RateSuggestedContentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['RateSuggestedContentResponse'] = _RATESUGGESTEDCONTENTRESPONSE

RateSuggestedContentResponse = _reflection.GeneratedProtocolMessageType('RateSuggestedContentResponse', (_message.Message,), dict(
  DESCRIPTOR = _RATESUGGESTEDCONTENTRESPONSE,
  __module__ = 'rate_suggested_content_response_pb2'
  # @@protoc_insertion_point(class_scope:RateSuggestedContentResponse.RateSuggestedContentResponse)
  ))
_sym_db.RegisterMessage(RateSuggestedContentResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n com.google.android.finsky.protosB\034RateSuggestedContentResponseP\001'))
# @@protoc_insertion_point(module_scope)
