# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_context_outer_class.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import context_outer_class_pb2 as context__outer__class__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='request_context_outer_class.proto',
  package='RequestContextOuterClass',
  syntax='proto2',
  serialized_pb=_b('\n!request_context_outer_class.proto\x12\x18RequestContextOuterClass\x1a\x19\x63ontext_outer_class.proto\"\xd3\x01\n\x0eRequestContext\x12\x13\n\x0bsessionData\x18\x02 \x01(\x0c\x12\x14\n\x0clanguageCode\x18\x07 \x01(\t\x12\x12\n\nclientType\x18\x08 \x01(\x05\x12\x15\n\rclientVersion\x18\t \x01(\x03\x12=\n\rnativeContext\x18\n \x01(\x0b\x32&.ContextOuterClass.NativeClientContext\x12\x11\n\trequestId\x18\x0b \x01(\t\x12\x19\n\x11isPrefetchRequest\x18\r \x01(\x08\x42V\n:com.google.commerce.payments.orchestration.proto.ui.commonB\x18RequestContextOuterClass')
  ,
  dependencies=[context__outer__class__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQUESTCONTEXT = _descriptor.Descriptor(
  name='RequestContext',
  full_name='RequestContextOuterClass.RequestContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionData', full_name='RequestContextOuterClass.RequestContext.sessionData', index=0,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='languageCode', full_name='RequestContextOuterClass.RequestContext.languageCode', index=1,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientType', full_name='RequestContextOuterClass.RequestContext.clientType', index=2,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientVersion', full_name='RequestContextOuterClass.RequestContext.clientVersion', index=3,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nativeContext', full_name='RequestContextOuterClass.RequestContext.nativeContext', index=4,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requestId', full_name='RequestContextOuterClass.RequestContext.requestId', index=5,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isPrefetchRequest', full_name='RequestContextOuterClass.RequestContext.isPrefetchRequest', index=6,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=302,
)

_REQUESTCONTEXT.fields_by_name['nativeContext'].message_type = context__outer__class__pb2._NATIVECLIENTCONTEXT
DESCRIPTOR.message_types_by_name['RequestContext'] = _REQUESTCONTEXT

RequestContext = _reflection.GeneratedProtocolMessageType('RequestContext', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTCONTEXT,
  __module__ = 'request_context_outer_class_pb2'
  # @@protoc_insertion_point(class_scope:RequestContextOuterClass.RequestContext)
  ))
_sym_db.RegisterMessage(RequestContext)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n:com.google.commerce.payments.orchestration.proto.ui.commonB\030RequestContextOuterClass'))
# @@protoc_insertion_point(module_scope)
