# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resolve_link.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='resolve_link.proto',
  package='ResolveLink',
  syntax='proto2',
  serialized_pb=_b('\n\x12resolve_link.proto\x12\x0bResolveLink\x1a\x0c\x63ommon.proto\"\xc6\x02\n\x0cResolvedLink\x12\x12\n\ndetailsUrl\x18\x01 \x01(\t\x12\x11\n\tbrowseUrl\x18\x02 \x01(\t\x12\x11\n\tsearchUrl\x18\x03 \x01(\t\x12\x33\n\x0e\x64irectPurchase\x18\x04 \x01(\x0b\x32\x1b.ResolveLink.DirectPurchase\x12\x0f\n\x07homeUrl\x18\x05 \x01(\t\x12\x33\n\x0eredeemGiftCard\x18\x06 \x01(\x0b\x32\x1b.ResolveLink.RedeemGiftCard\x12\x18\n\x10serverLogsCookie\x18\x07 \x01(\x0c\x12\x1c\n\x05\x64ocid\x18\x08 \x01(\x0b\x32\r.Common.Docid\x12\x13\n\x0bwishlistUrl\x18\t \x01(\t\x12\x0f\n\x07\x62\x61\x63kend\x18\n \x01(\x05\x12\r\n\x05query\x18\x0b \x01(\t\x12\x14\n\x0cmyAccountUrl\x18\x0c \x01(\t\"c\n\x0e\x44irectPurchase\x12\x12\n\ndetailsUrl\x18\x01 \x01(\t\x12\x15\n\rpurchaseDocid\x18\x02 \x01(\t\x12\x13\n\x0bparentDocid\x18\x03 \x01(\t\x12\x11\n\tofferType\x18\x04 \x01(\x05\"=\n\x0eRedeemGiftCard\x12\x13\n\x0bprefillCode\x18\x01 \x01(\t\x12\x16\n\x0epartnerPayload\x18\x02 \x01(\tB/\n com.google.android.finsky.protosB\x0bResolveLink')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RESOLVEDLINK = _descriptor.Descriptor(
  name='ResolvedLink',
  full_name='ResolveLink.ResolvedLink',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detailsUrl', full_name='ResolveLink.ResolvedLink.detailsUrl', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='browseUrl', full_name='ResolveLink.ResolvedLink.browseUrl', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='searchUrl', full_name='ResolveLink.ResolvedLink.searchUrl', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='directPurchase', full_name='ResolveLink.ResolvedLink.directPurchase', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='homeUrl', full_name='ResolveLink.ResolvedLink.homeUrl', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='redeemGiftCard', full_name='ResolveLink.ResolvedLink.redeemGiftCard', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serverLogsCookie', full_name='ResolveLink.ResolvedLink.serverLogsCookie', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='docid', full_name='ResolveLink.ResolvedLink.docid', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wishlistUrl', full_name='ResolveLink.ResolvedLink.wishlistUrl', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='backend', full_name='ResolveLink.ResolvedLink.backend', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='query', full_name='ResolveLink.ResolvedLink.query', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='myAccountUrl', full_name='ResolveLink.ResolvedLink.myAccountUrl', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=376,
)


_DIRECTPURCHASE = _descriptor.Descriptor(
  name='DirectPurchase',
  full_name='ResolveLink.DirectPurchase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detailsUrl', full_name='ResolveLink.DirectPurchase.detailsUrl', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='purchaseDocid', full_name='ResolveLink.DirectPurchase.purchaseDocid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parentDocid', full_name='ResolveLink.DirectPurchase.parentDocid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offerType', full_name='ResolveLink.DirectPurchase.offerType', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=477,
)


_REDEEMGIFTCARD = _descriptor.Descriptor(
  name='RedeemGiftCard',
  full_name='ResolveLink.RedeemGiftCard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prefillCode', full_name='ResolveLink.RedeemGiftCard.prefillCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnerPayload', full_name='ResolveLink.RedeemGiftCard.partnerPayload', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=479,
  serialized_end=540,
)

_RESOLVEDLINK.fields_by_name['directPurchase'].message_type = _DIRECTPURCHASE
_RESOLVEDLINK.fields_by_name['redeemGiftCard'].message_type = _REDEEMGIFTCARD
_RESOLVEDLINK.fields_by_name['docid'].message_type = common__pb2._DOCID
DESCRIPTOR.message_types_by_name['ResolvedLink'] = _RESOLVEDLINK
DESCRIPTOR.message_types_by_name['DirectPurchase'] = _DIRECTPURCHASE
DESCRIPTOR.message_types_by_name['RedeemGiftCard'] = _REDEEMGIFTCARD

ResolvedLink = _reflection.GeneratedProtocolMessageType('ResolvedLink', (_message.Message,), dict(
  DESCRIPTOR = _RESOLVEDLINK,
  __module__ = 'resolve_link_pb2'
  # @@protoc_insertion_point(class_scope:ResolveLink.ResolvedLink)
  ))
_sym_db.RegisterMessage(ResolvedLink)

DirectPurchase = _reflection.GeneratedProtocolMessageType('DirectPurchase', (_message.Message,), dict(
  DESCRIPTOR = _DIRECTPURCHASE,
  __module__ = 'resolve_link_pb2'
  # @@protoc_insertion_point(class_scope:ResolveLink.DirectPurchase)
  ))
_sym_db.RegisterMessage(DirectPurchase)

RedeemGiftCard = _reflection.GeneratedProtocolMessageType('RedeemGiftCard', (_message.Message,), dict(
  DESCRIPTOR = _REDEEMGIFTCARD,
  __module__ = 'resolve_link_pb2'
  # @@protoc_insertion_point(class_scope:ResolveLink.RedeemGiftCard)
  ))
_sym_db.RegisterMessage(RedeemGiftCard)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n com.google.android.finsky.protosB\013ResolveLink'))
# @@protoc_insertion_point(module_scope)
