# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tax_info_form_outer_class.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ui_field_outer_class_pb2 as ui__field__outer__class__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tax_info_form_outer_class.proto',
  package='TaxInfoFormOuterClass',
  syntax='proto2',
  serialized_pb=_b('\n\x1ftax_info_form_outer_class.proto\x12\x15TaxInfoFormOuterClass\x1a\x1aui_field_outer_class.proto\"`\n\x10TaxInfoFormValue\x12\x15\n\rtaxInfoFormId\x18\x01 \x01(\t\x12\x35\n\x0ctaxInfoValue\x18\x03 \x03(\x0b\x32\x1f.UiFieldOuterClass.UiFieldValue\"Z\n\x0bTaxInfoForm\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x30\n\x0ctaxInfoField\x18\x04 \x03(\x0b\x32\x1a.UiFieldOuterClass.UiFieldBb\nIcom.google.commerce.payments.orchestration.proto.ui.common.components.taxB\x15TaxInfoFormOuterClass')
  ,
  dependencies=[ui__field__outer__class__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TAXINFOFORMVALUE = _descriptor.Descriptor(
  name='TaxInfoFormValue',
  full_name='TaxInfoFormOuterClass.TaxInfoFormValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taxInfoFormId', full_name='TaxInfoFormOuterClass.TaxInfoFormValue.taxInfoFormId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='taxInfoValue', full_name='TaxInfoFormOuterClass.TaxInfoFormValue.taxInfoValue', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=182,
)


_TAXINFOFORM = _descriptor.Descriptor(
  name='TaxInfoForm',
  full_name='TaxInfoFormOuterClass.TaxInfoForm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TaxInfoFormOuterClass.TaxInfoForm.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='TaxInfoFormOuterClass.TaxInfoForm.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='taxInfoField', full_name='TaxInfoFormOuterClass.TaxInfoForm.taxInfoField', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=274,
)

_TAXINFOFORMVALUE.fields_by_name['taxInfoValue'].message_type = ui__field__outer__class__pb2._UIFIELDVALUE
_TAXINFOFORM.fields_by_name['taxInfoField'].message_type = ui__field__outer__class__pb2._UIFIELD
DESCRIPTOR.message_types_by_name['TaxInfoFormValue'] = _TAXINFOFORMVALUE
DESCRIPTOR.message_types_by_name['TaxInfoForm'] = _TAXINFOFORM

TaxInfoFormValue = _reflection.GeneratedProtocolMessageType('TaxInfoFormValue', (_message.Message,), dict(
  DESCRIPTOR = _TAXINFOFORMVALUE,
  __module__ = 'tax_info_form_outer_class_pb2'
  # @@protoc_insertion_point(class_scope:TaxInfoFormOuterClass.TaxInfoFormValue)
  ))
_sym_db.RegisterMessage(TaxInfoFormValue)

TaxInfoForm = _reflection.GeneratedProtocolMessageType('TaxInfoForm', (_message.Message,), dict(
  DESCRIPTOR = _TAXINFOFORM,
  __module__ = 'tax_info_form_outer_class_pb2'
  # @@protoc_insertion_point(class_scope:TaxInfoFormOuterClass.TaxInfoForm)
  ))
_sym_db.RegisterMessage(TaxInfoForm)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\nIcom.google.commerce.payments.orchestration.proto.ui.common.components.taxB\025TaxInfoFormOuterClass'))
# @@protoc_insertion_point(module_scope)
