# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: username_password.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import legal_message_outer_class_pb2 as legal__message__outer__class__pb2
import ui_field_outer_class_pb2 as ui__field__outer__class__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='username_password.proto',
  package='UsernamePassword',
  syntax='proto2',
  serialized_pb=_b('\n\x17username_password.proto\x12\x10UsernamePassword\x1a\x1flegal_message_outer_class.proto\x1a\x1aui_field_outer_class.proto\"\xc7\x01\n\x19UsernamePasswordFormValue\x12\x31\n\x08username\x18\x01 \x01(\x0b\x32\x1f.UiFieldOuterClass.UiFieldValue\x12\x31\n\x08password\x18\x02 \x01(\x0b\x32\x1f.UiFieldOuterClass.UiFieldValue\x12\x16\n\x0e\x65ncryptionType\x18\x03 \x01(\x05\x12\x14\n\x0clegalDocData\x18\x04 \x01(\t\x12\x16\n\x0ehashedDeviceId\x18\x05 \x01(\t\"\xc0\x02\n\x14UsernamePasswordForm\x12\n\n\x02id\x18\x01 \x01(\t\x12\x16\n\x0e\x65ncryptionType\x18\x02 \x01(\x05\x12 \n\x18\x63redentialsEncryptionKey\x18\x04 \x01(\x0c\x12\x31\n\rusernameField\x18\x05 \x01(\x0b\x32\x1a.UiFieldOuterClass.UiField\x12\x31\n\rpasswordField\x18\x06 \x01(\x0b\x32\x1a.UiFieldOuterClass.UiField\x12\x15\n\rloginHelpHtml\x18\x07 \x01(\t\x12:\n\x0clegalMessage\x18\x08 \x01(\x0b\x32$.LegalMessageOuterClass.LegalMessage\x12\r\n\x05title\x18\t \x01(\t\x12\x1a\n\x12vendorSpecificSalt\x18\n \x01(\tBj\nVcom.google.commerce.payments.orchestration.proto.ui.common.components.instrument.typesB\x10UsernamePassword')
  ,
  dependencies=[legal__message__outer__class__pb2.DESCRIPTOR,ui__field__outer__class__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_USERNAMEPASSWORDFORMVALUE = _descriptor.Descriptor(
  name='UsernamePasswordFormValue',
  full_name='UsernamePassword.UsernamePasswordFormValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='UsernamePassword.UsernamePasswordFormValue.username', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='UsernamePassword.UsernamePasswordFormValue.password', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encryptionType', full_name='UsernamePassword.UsernamePasswordFormValue.encryptionType', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='legalDocData', full_name='UsernamePassword.UsernamePasswordFormValue.legalDocData', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hashedDeviceId', full_name='UsernamePassword.UsernamePasswordFormValue.hashedDeviceId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=306,
)


_USERNAMEPASSWORDFORM = _descriptor.Descriptor(
  name='UsernamePasswordForm',
  full_name='UsernamePassword.UsernamePasswordForm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UsernamePassword.UsernamePasswordForm.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encryptionType', full_name='UsernamePassword.UsernamePasswordForm.encryptionType', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='credentialsEncryptionKey', full_name='UsernamePassword.UsernamePasswordForm.credentialsEncryptionKey', index=2,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='usernameField', full_name='UsernamePassword.UsernamePasswordForm.usernameField', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='passwordField', full_name='UsernamePassword.UsernamePasswordForm.passwordField', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loginHelpHtml', full_name='UsernamePassword.UsernamePasswordForm.loginHelpHtml', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='legalMessage', full_name='UsernamePassword.UsernamePasswordForm.legalMessage', index=6,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='UsernamePassword.UsernamePasswordForm.title', index=7,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vendorSpecificSalt', full_name='UsernamePassword.UsernamePasswordForm.vendorSpecificSalt', index=8,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=629,
)

_USERNAMEPASSWORDFORMVALUE.fields_by_name['username'].message_type = ui__field__outer__class__pb2._UIFIELDVALUE
_USERNAMEPASSWORDFORMVALUE.fields_by_name['password'].message_type = ui__field__outer__class__pb2._UIFIELDVALUE
_USERNAMEPASSWORDFORM.fields_by_name['usernameField'].message_type = ui__field__outer__class__pb2._UIFIELD
_USERNAMEPASSWORDFORM.fields_by_name['passwordField'].message_type = ui__field__outer__class__pb2._UIFIELD
_USERNAMEPASSWORDFORM.fields_by_name['legalMessage'].message_type = legal__message__outer__class__pb2._LEGALMESSAGE
DESCRIPTOR.message_types_by_name['UsernamePasswordFormValue'] = _USERNAMEPASSWORDFORMVALUE
DESCRIPTOR.message_types_by_name['UsernamePasswordForm'] = _USERNAMEPASSWORDFORM

UsernamePasswordFormValue = _reflection.GeneratedProtocolMessageType('UsernamePasswordFormValue', (_message.Message,), dict(
  DESCRIPTOR = _USERNAMEPASSWORDFORMVALUE,
  __module__ = 'username_password_pb2'
  # @@protoc_insertion_point(class_scope:UsernamePassword.UsernamePasswordFormValue)
  ))
_sym_db.RegisterMessage(UsernamePasswordFormValue)

UsernamePasswordForm = _reflection.GeneratedProtocolMessageType('UsernamePasswordForm', (_message.Message,), dict(
  DESCRIPTOR = _USERNAMEPASSWORDFORM,
  __module__ = 'username_password_pb2'
  # @@protoc_insertion_point(class_scope:UsernamePassword.UsernamePasswordForm)
  ))
_sym_db.RegisterMessage(UsernamePasswordForm)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\nVcom.google.commerce.payments.orchestration.proto.ui.common.components.instrument.typesB\020UsernamePassword'))
# @@protoc_insertion_point(module_scope)
